baseURL = "https://eightsuzuki.github.io/"
languageCode = 'en-us'
title = "mysite"
theme = "hugo-bearblog"


author = "Jane Doe"
copyright = "Copyright © 2020, Jane Doe."

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  images = ["images/share.png"]
  title = "Hugo ʕ•ᴥ•ʔ Bear"
  mainSections = ["content/about", "blog"]
  hideMadeWithLine = true

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/amuyikam/"
    
[[params.social]]
    name = "Qiita"
    icon = "fab fa-qiita fa-2x"
    weight = 3
    url = "https://qiita.com/amuyikam"